In [1]:
import scipy.io as scio
import numpy as np    
import matplotlib.pyplot as plt
from scipy.misc import imsave

In [2]:
path='Dataset/Subject_new_'
labeled_images = []
labeled_colorimages = []

In [3]:
def load_subject(subject_no):
    local_path=path+subject_no+'/Sub_'+subject_no+'.mat'
    sub = scio.loadmat(local_path)
    print (sub.keys())
    return sub
    
def reshape(ndarray):
    ndarray_reshaped = np.array(ndarray.tolist())
    ndarray_reshaped = ndarray_reshaped.reshape(ndarray.shape).transpose(2,0,1)
    print (ndarray_reshaped.shape)
    return ndarray_reshaped

def get_gt_ids(subject_no):
    local_path=path+subject_no+'/gt_id.mat'
    gt_id = scio.loadmat(local_path)
    print (gt_id.keys())
    gt_id_list = gt_id['fr1']
    print(gt_id_list)
    gt_list = []
    for item in gt_id_list:
        gt_list.append(item[0])
    return gt_list
    
def crop_image(image,left_bound,right_bound):
    image = image[:,left_bound:right_bound]
    return image
    

In [4]:
sub = load_subject(str(2))
sub_images = sub['images']


dict_keys(['grader1', '__globals__', 'automaticLayersDME', '__header__', 'images', 'automaticLayersNormal', 'grader_SJ', 'grader2', 'manualLayers2', 'manualLayers1', '__version__'])


In [5]:
for sub_index in range(10):
    sub=load_subject(str(sub_index+1))
    sub_images = sub['images']
    images_reshaped = reshape(sub_images)
    print (images_reshaped.shape)
    manualLayer = sub['manualLayers1']
    manualLayer_reshaped=reshape(manualLayer)
    print (manualLayer_reshaped.shape)
    left_bounds = [136,121,117,109,137,146,134,120,124,140]
    right_bounds = [636,621,617,609,637,646,634,620,624,640]
    gt_id_list = []
    gt_id_list = get_gt_ids(str(sub_index+1))
    for i in gt_id_list:
        test = manualLayer_reshaped[i-1]
        #print (test)
        test=crop_image(test,left_bounds[sub_index],right_bounds[sub_index])
        for j in range(8):
            for k in range(500):
                if(test[j][k]==0):
                    test[j][k] = test[j][k-1]
        res_image = np.zeros((496,500))
        color = np.zeros((496,500,3))
        for j in range(7):
            for k in range(500):
                for a in range(test[j][k], test[j+1][k]):
                        res_image[a][k] = j+1
        labeled_images.append(res_image)
        for j in range(496):
            for k in range(500):
                if(res_image[j][k]==0):
                    color[j][k] = [0,0,0]
                if(res_image[j][k]==1):
                    color[j][k] = [128,0,0]
                if(res_image[j][k]==2):
                    color[j][k] = [0,128,0]
                if(res_image[j][k]==3):
                    color[j][k] = [128,128,0] 
                if(res_image[j][k]==4):
                    color[j][k] = [0,128,128]
                if(res_image[j][k]==5):
                    color[j][k] = [64,0,0]
                if(res_image[j][k]==6):
                    color[j][k] = [192,0,0]
                if(res_image[j][k]==7):
                    color[j][k] = [64,128,0]
                if(res_image[j][k]==9):
                    color[j][k] = [0,64,128]
        labeled_colorimages.append(color)
    

dict_keys(['grader1', '__globals__', 'automaticLayersDME', '__header__', 'images', 'automaticLayersNormal', 'grader_SJ', 'grader2', 'manualLayers2', 'manualLayers1', '__version__'])
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
dict_keys(['__globals__', '__header__', '__version__', 'fr1'])
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
dict_keys(['grader1', '__globals__', 'automaticLayersDME', '__header__', 'images', 'automaticLayersNormal', 'grader_SJ', 'grader2', 'manualLayers2', 'manualLayers1', '__version__'])
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
dict_keys(['__globals__', '__header__', '__version__', 'fr1'])
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
dict_keys(['grader1', '__globals__', 'automaticLayersDME', '__header__', 'images', 'automaticLayersNormal', 'grader_SJ', 'grader2', 'manualLayers2', 'manualLayers1', '__version__'])
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
dict_keys(['__globals__', 

In [6]:
print (len(labeled_images))

110


In [7]:
print (labeled_images[0].shape)

(496, 500)


In [8]:
print (len(labeled_colorimages))

110


In [9]:
print (labeled_colorimages[0])

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [17]:
for item in range(110):
    imsave('Dataset/Colored_'+str(item+1)+'.png',labeled_colorimages[item])