In [1]:
import scipy.io as scio
import numpy as np    
import matplotlib.pyplot as plt
from scipy.misc import imsave

In [2]:
path='Dataset/Subject_new_'
labeled_images = []
labeled_colorimages = []
images_modified=[]

In [3]:
def load_subject(subject_no):
    local_path=path+subject_no+'/Sub_'+subject_no+'.mat'
    sub = scio.loadmat(local_path)
    print (sub.keys())
    return sub
    
def reshape(ndarray):
    ndarray_reshaped = np.array(ndarray.tolist())
    ndarray_reshaped = ndarray_reshaped.reshape(ndarray.shape).transpose(2,0,1)
    print (ndarray_reshaped.shape)
    return ndarray_reshaped

def get_gt_ids(subject_no):
    local_path=path+subject_no+'/gt_id.mat'
    gt_id = scio.loadmat(local_path)
    print (gt_id.keys())
    gt_id_list = gt_id['fr1']
    print(gt_id_list)
    gt_list = []
    for item in gt_id_list:
        gt_list.append(item[0])
    return gt_list
    
def crop_image(image,left_bound,right_bound):
    image = image[:,left_bound:right_bound]
    return image
    

In [4]:
sub = load_subject(str(2))
sub_images = sub['images']


['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']


In [5]:
for sub_index in range(10):
    sub=load_subject(str(sub_index+1))
    sub_images = sub['images']
    images_reshaped = reshape(sub_images)
    print (images_reshaped.shape)
    manualLayer = sub['manualLayers1']
    manualLayer_reshaped=reshape(manualLayer)
    print (manualLayer_reshaped.shape)
    left_bounds = [136,121,117,109,137,146,134,120,124,140]
    right_bounds = [636,621,617,609,637,646,634,620,624,640]
    gt_id_list = []
    gt_id_list = get_gt_ids(str(sub_index+1))
    for i in gt_id_list:
        test = manualLayer_reshaped[i-1]
        #print (test)
        test=crop_image(test,left_bounds[sub_index],right_bounds[sub_index])
        image_modified=crop_image(images_reshaped[i-1],left_bounds[sub_index],right_bounds[sub_index])
        images_modified.append(image_modified)
        for j in range(8):
            for k in range(500):
                if(test[j][k]==0):
                    test[j][k] = test[j][k-1]
        res_image = np.zeros((496,500))
        color = np.zeros((496,500,3))
        for j in range(7):
            for k in range(500):
                for a in range(test[j][k], test[j+1][k]):
                        res_image[a][k] = j+1
        labeled_images.append(res_image)
        for j in range(496):
            for k in range(500):
                if(res_image[j][k]==0):
                    color[j][k] = [0,0,0]
                if(res_image[j][k]==1):
                    color[j][k] = [128,0,0]
                if(res_image[j][k]==2):
                    color[j][k] = [0,128,0]
                if(res_image[j][k]==3):
                    color[j][k] = [128,128,0] 
                if(res_image[j][k]==4):
                    color[j][k] = [0,128,128]
                if(res_image[j][k]==5):
                    color[j][k] = [64,0,0]
                if(res_image[j][k]==6):
                    color[j][k] = [192,0,0]
                if(res_image[j][k]==7):
                    color[j][k] = [64,128,0]
                if(res_image[j][k]==9):
                    color[j][k] = [0,64,128]
        labeled_colorimages.append(color)
    

['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]

In [6]:
print (len(labeled_images))

110


In [7]:
print (len(images_modified))

110


In [8]:
print (labeled_images[0].shape)

(496, 500)


In [9]:
print (len(labeled_colorimages))

110


In [10]:
print (labeled_colorimages[0])

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [10]:
for item in range(110):
    imsave('Dataset/Colored_'+str(item+1)+'.png',labeled_colorimages[item])

In [11]:
print (images_modified[0].shape)

(496, 500)


In [12]:
train_images = []
dummy_train_labels = []


In [13]:
for i in range(len(images_modified)) :
        for j in range(7) :
            train_image = crop_image(images_modified[i],j*64,(j+1)*64)
            train_images.append(train_image)

In [14]:
print (len(train_images))

770


In [15]:
for item in range(len(train_images)) :
    imsave('Dataset/Train_images/image_'+str(item+1)+'.png',train_images[item])

In [16]:
for i in range(len(labeled_images)) :
    for j in range(7) :
        dummy_train_label = crop_image(labeled_images[i],j*64,(j+1)*64)
        dummy_train_labels.append(dummy_train_label)

In [17]:
print (len(dummy_train_labels))

770


In [18]:
print (dummy_train_labels[0].shape)

(496, 64)


In [22]:
train_labels  = np.zeros((770,496,64,8))

In [23]:
print (dummy_train_labels[0][0][0])

0.0


In [24]:
for i in range(len(dummy_train_labels)) :
    for j in range(496) :
        for k in range(64):
            if(dummy_train_labels[i][j][k] == 0):
                train_labels[i][j][k][0] = 1
            if(dummy_train_labels[i][j][k] == 1):
                train_labels[i][j][k][1] = 1
            if(dummy_train_labels[i][j][k] == 2):
                train_labels[i][j][k][2] = 1
            if(dummy_train_labels[i][j][k] == 3):
                train_labels[i][j][k][3] = 1
            if(dummy_train_labels[i][j][k] == 4):
                train_labels[i][j][k][4] = 1
            if(dummy_train_labels[i][j][k] == 5):
                train_labels[i][j][k][5] = 1
            if(dummy_train_labels[i][j][k] == 6):
                train_labels[i][j][k][6] = 1
            if(dummy_train_labels[i][j][k] == 7):
                train_labels[i][j][k][7] = 1

In [25]:
print (len(train_labels))

770


In [26]:
print (type(train_labels))

<type 'numpy.ndarray'>


In [27]:
print (train_labels[0][0][0])

[ 1.  0.  0.  0.  0.  0.  0.  0.]


In [28]:
np.save('train_labels.npy',train_labels)

In [29]:
p = np.load('train_labels.npy')

In [30]:
print(p[0][0][0])

[ 1.  0.  0.  0.  0.  0.  0.  0.]
